### PR TITLE
I have altered your library

### PR DESCRIPTION
**Pull request by bitemyapp**
and made it twice as useful. Pray I do not alter it further.

### CODE REVIEW

**Comment by gfredericks** [comment]
This definitely seems like it could be useful, but I'm worried that it might constitute scope creep.

**Comment by bitemyapp** [comment]
@gfredericks you leave me no choice!

**Comment by gfredericks** [comment]
oh dear.

**Comment by ifesdjeen** [comment]
In my opinion, this belongs to the other library, functionality is overwhelming. Maybe create a lib names `seventy-two`?

**Pull request closed without merging**
